/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './index';
import * as import2 from '@angular/core/src/di/injector';
class WalmooNFCModuleInjector extends import0.NgModuleInjector<import1.WalmooNFCModule> {
  _WalmooNFCModule_0:import1.WalmooNFCModule;
  __Window_1:any;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _Window_1():any {
    if ((this.__Window_1 == (null as any))) { (this.__Window_1 = import1.window); }
    return this.__Window_1;
  }
  createInternal():import1.WalmooNFCModule {
    this._WalmooNFCModule_0 = new import1.WalmooNFCModule();
    return this._WalmooNFCModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.WalmooNFCModule)) { return this._WalmooNFCModule_0; }
    if ((token === import1.Window)) { return this._Window_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const WalmooNFCModuleNgFactory:import0.NgModuleFactory<import1.WalmooNFCModule> = new import0.NgModuleFactory(WalmooNFCModuleInjector,import1.WalmooNFCModule);